/* eslint-disable react-hooks/exhaustive-deps */
import { initializeApp } from "firebase/app";
import {
  collection,
  doc,
  getDoc,
  getDocs,
  getFirestore,
} from "firebase/firestore";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { firebaseApp } from "../firebase";
import { getCalendarList } from "../functions/localStorage";
import styles from "../styles/Home.module.css";
import { calendarList } from "../types/localStorage";

const Home: NextPage = () => {
  const [calendarList, setCalendarList] = useState<calendarList>([]);
  useEffect(() => {
    console.log("get");
    const tmpCalendarList = getCalendarList();
    setCalendarList(tmpCalendarList);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {calendarList.map((calendar) => (
          <a
            href={`http://localhost:3000/calendar/${calendar.id}}`}
            key={calendar.id}
          >
            {calendar.name}
          </a>
        ))}
        <a href="http://localhost:3000/createCalendar">新規作成</a>
      </div>
    </div>
  );
};

export default Home;
